version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_sphere_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
      # - APP_ENV=dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
