version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_sphere
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
